/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Report;

import java.awt.HeadlessException;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import net.sf.jasperreports.engine.JRException;


/**
 *
 * @author LENOVO
 */
public class Dataminuman extends javax.swing.JFrame {

    /**
     * Creates new form Minuman
     */
    public Dataminuman() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        tid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        tha = new javax.swing.JTextField();
        cbka = new javax.swing.JComboBox<>();
        cbu = new javax.swing.JComboBox<>();
        bsub = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        UpdateDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        tid1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tnama1 = new javax.swing.JTextField();
        tha1 = new javax.swing.JTextField();
        cbka1 = new javax.swing.JComboBox<>();
        cbu1 = new javax.swing.JComboBox<>();
        dupdate = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        DeleteDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        tid2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tnama2 = new javax.swing.JTextField();
        tha2 = new javax.swing.JTextField();
        cbka2 = new javax.swing.JComboBox<>();
        cbu2 = new javax.swing.JComboBox<>();
        bya = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btidak = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtab = new javax.swing.JTable();
        bu = new javax.swing.JButton();
        bd = new javax.swing.JButton();
        bi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bx = new javax.swing.JButton();
        bcetak = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 33, 146, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 38, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 78, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kategori");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 118, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 158, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ukuran");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 198, -1, -1));
        jPanel1.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 73, 146, -1));

        tha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thaActionPerformed(evt);
            }
        });
        jPanel1.add(tha, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 153, 146, -1));

        cbka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kopi", "Susu", "Matcha", "Boba", "Coklat", "Teh" }));
        jPanel1.add(cbka, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 113, -1, -1));

        cbu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));
        jPanel1.add(cbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 193, -1, -1));

        bsub.setBackground(new java.awt.Color(204, 204, 255));
        bsub.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bsub.setText("Submit");
        bsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubActionPerformed(evt);
            }
        });
        jPanel1.add(bsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 233, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Report/pngtree-3d-render-of-the-interior-of-a-cozy-cafe-restaurant-image_3811953.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 280));

        javax.swing.GroupLayout InsertDialogLayout = new javax.swing.GroupLayout(InsertDialog.getContentPane());
        InsertDialog.getContentPane().setLayout(InsertDialogLayout);
        InsertDialogLayout.setHorizontalGroup(
            InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InsertDialogLayout.setVerticalGroup(
            InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tid1.setEnabled(false);
        jPanel3.add(tid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 33, 146, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 38, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nama");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 78, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kategori");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 118, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Harga");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 158, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ukuran");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 198, -1, -1));
        jPanel3.add(tnama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 73, 146, -1));

        tha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tha1ActionPerformed(evt);
            }
        });
        jPanel3.add(tha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 153, 146, -1));

        cbka1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kopi", "Susu", "Matcha", "Boba", "Coklat", "Teh" }));
        jPanel3.add(cbka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 113, -1, -1));

        cbu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));
        jPanel3.add(cbu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 193, -1, -1));

        dupdate.setBackground(new java.awt.Color(204, 204, 255));
        dupdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dupdate.setText("Update");
        dupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dupdateActionPerformed(evt);
            }
        });
        jPanel3.add(dupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 233, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Report/pngtree-3d-render-of-the-interior-of-a-cozy-cafe-restaurant-image_3811953.jpg"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 280));

        javax.swing.GroupLayout UpdateDialogLayout = new javax.swing.GroupLayout(UpdateDialog.getContentPane());
        UpdateDialog.getContentPane().setLayout(UpdateDialogLayout);
        UpdateDialogLayout.setHorizontalGroup(
            UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UpdateDialogLayout.setVerticalGroup(
            UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tid2.setEnabled(false);
        jPanel4.add(tid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 146, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nama");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Kategori");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Harga");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ukuran");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        tnama2.setEnabled(false);
        jPanel4.add(tnama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 146, -1));

        tha2.setEnabled(false);
        tha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tha2ActionPerformed(evt);
            }
        });
        jPanel4.add(tha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 146, -1));

        cbka2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kopi", "Susu", "Matcha", "Boba", "Coklat", "Teh" }));
        cbka2.setEnabled(false);
        jPanel4.add(cbka2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        cbu2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));
        cbu2.setEnabled(false);
        jPanel4.add(cbu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        bya.setBackground(new java.awt.Color(204, 204, 255));
        bya.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bya.setText("Ya");
        bya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byaActionPerformed(evt);
            }
        });
        jPanel4.add(bya, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 60, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("APAKAH YAKIN INGIN MENGHAPUS DATA INI ?");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btidak.setBackground(new java.awt.Color(204, 204, 255));
        btidak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btidak.setText("Tidak");
        btidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btidakActionPerformed(evt);
            }
        });
        jPanel4.add(btidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 260, 60, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Report/pngtree-3d-render-of-the-interior-of-a-cozy-cafe-restaurant-image_3811953.jpg"))); // NOI18N
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 300));

        javax.swing.GroupLayout DeleteDialogLayout = new javax.swing.GroupLayout(DeleteDialog.getContentPane());
        DeleteDialog.getContentPane().setLayout(DeleteDialogLayout);
        DeleteDialogLayout.setHorizontalGroup(
            DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DeleteDialogLayout.setVerticalGroup(
            DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Kategori", "Harga", "Ukuran"
            }
        ));
        jtab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtab);
        if (jtab.getColumnModel().getColumnCount() > 0) {
            jtab.getColumnModel().getColumn(0).setMaxWidth(50);
            jtab.getColumnModel().getColumn(1).setMinWidth(100);
            jtab.getColumnModel().getColumn(1).setMaxWidth(100);
            jtab.getColumnModel().getColumn(4).setMinWidth(50);
            jtab.getColumnModel().getColumn(4).setMaxWidth(50);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 460, 240));

        bu.setBackground(new java.awt.Color(204, 204, 255));
        bu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bu.setText("Update");
        bu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buActionPerformed(evt);
            }
        });
        jPanel2.add(bu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        bd.setBackground(new java.awt.Color(204, 204, 255));
        bd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bd.setText("Delete");
        bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdActionPerformed(evt);
            }
        });
        jPanel2.add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 70, -1));

        bi.setBackground(new java.awt.Color(204, 204, 255));
        bi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bi.setText("Insert");
        bi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biActionPerformed(evt);
            }
        });
        jPanel2.add(bi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 70, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DATA MINUMAN");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        bx.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bx.setForeground(new java.awt.Color(255, 0, 0));
        bx.setText("X");
        bx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxActionPerformed(evt);
            }
        });
        jPanel2.add(bx, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 0, 36, 36));

        bcetak.setBackground(new java.awt.Color(204, 204, 255));
        bcetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bcetak.setText("Cetak");
        bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetakActionPerformed(evt);
            }
        });
        jPanel2.add(bcetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 70, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Report/pngtree-3d-render-of-the-interior-of-a-cozy-cafe-restaurant-image_3811953.jpg"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // semua sel tidak bisa diubah langsung
        }
    };
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Kategori");
        model.addColumn("Harga");
        model.addColumn("Ukuran");

// load data dari DB
        try (
                Connection conn = Koneksi.getConnection(); Statement st = conn.createStatement(); ResultSet rs = st.executeQuery("SELECT * FROM dataminuman ORDER BY id_minuman")) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_minuman"),
                    rs.getString("nama"),
                    rs.getString("kategori"),
                    rs.getInt("harga"),
                    rs.getString("ukuran")
                });
            }

            jtab.setModel(model); // tampilkan ke JTable
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }

    }

    private void clear() {
        tid.setText("");
        tnama.setText("");
        cbka.setSelectedIndex(0);
        tha.setText("");
        cbu.setSelectedIndex(0);

        tid.setEditable(true);
    }


    private void bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdActionPerformed
        // TODO add your handling code here:
        int row = jtab.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau dihapus!");
            return;
        }

        // ambil data dari tabel
        String id = jtab.getValueAt(row, 0).toString();
        String nama = jtab.getValueAt(row, 1).toString();
        String kategori = jtab.getValueAt(row, 2).toString();
        String harga = jtab.getValueAt(row, 3).toString();
        String ukuran = jtab.getValueAt(row, 4).toString();

        // tampilkan ke dialog delete
        tid2.setText(id);
        tnama2.setText(nama);
        cbka2.setSelectedItem(kategori);
        tha2.setText(harga);
        cbu2.setSelectedItem(ukuran);

        // semua field tidak bisa diedit
        tid2.setEditable(false);
        tnama2.setEditable(false);
        cbka2.setEnabled(false);
        tha2.setEditable(false);
        cbu2.setEnabled(false);

        DeleteDialog.pack();
        DeleteDialog.setLocationRelativeTo(this);
        DeleteDialog.setVisible(true);


    }//GEN-LAST:event_bdActionPerformed

    private void biActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biActionPerformed
        // TODO add your handling code here:
        clear();
        InsertDialog.pack(); // atur ulang ukuran sesuai desain
        InsertDialog.setLocationRelativeTo(this);
        InsertDialog.setVisible(true);
    }//GEN-LAST:event_biActionPerformed

    private void jtabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabMouseClicked
        // TODO add your handling code here:
        tid.setText(jtab.getValueAt(jtab.getSelectedRow(), 0).toString());
        tnama.setText(jtab.getValueAt(jtab.getSelectedRow(), 1).toString());
        cbka.setSelectedItem(jtab.getValueAt(jtab.getSelectedRow(), 2).toString());
        tha.setText(jtab.getValueAt(jtab.getSelectedRow(), 3).toString());
        cbu.setSelectedItem(jtab.getValueAt(jtab.getSelectedRow(), 4).toString());

        tid.setEditable(false);
    }//GEN-LAST:event_jtabMouseClicked

    private void buActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buActionPerformed
        // TODO add your handling code here:
        int row = jtab.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu untuk diupdate!");
            return;
        }

        // Ambil data dari row
        String id = jtab.getValueAt(row, 0).toString();
        String nama = jtab.getValueAt(row, 1).toString();
        String kategori = jtab.getValueAt(row, 2).toString();
        String harga = jtab.getValueAt(row, 3).toString();
        String ukuran = jtab.getValueAt(row, 4).toString();

        // Masukkan ke dialog
        tid1.setText(id);
        tid1.setEditable(false); // biasanya ID tidak boleh diubah
        tnama1.setText(nama);
        cbka1.setSelectedItem(kategori);
        tha1.setText(harga);
        cbu1.setSelectedItem(ukuran);

        UpdateDialog.pack();
        UpdateDialog.setLocationRelativeTo(this);
        UpdateDialog.setVisible(true);
    }//GEN-LAST:event_buActionPerformed

    private void thaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thaActionPerformed

    private void bsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(tid.getText());
            String nama = tnama.getText();
            String kategori = cbka.getSelectedItem().toString();
            int harga = Integer.parseInt(tha.getText());
            String ukuran = cbu.getSelectedItem().toString();

            Connection conn = Koneksi.getConnection();
            String sql = "INSERT INTO dataminuman (id_minuman, nama, kategori, harga, ukuran) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, id);
            ps.setString(2, nama);
            ps.setString(3, kategori);
            ps.setInt(4, harga);
            ps.setString(5, ukuran);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            
            tampilData();
            clear();
            InsertDialog.setVisible(false);

        } catch (NumberFormatException | SQLException e) {
            System.out.println("Gagal insert: " + e.getMessage());
        }
    }//GEN-LAST:event_bsubActionPerformed

    private void tha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tha1ActionPerformed

    private void dupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dupdateActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE dataminuman SET nama = ?, kategori = ?, harga = ?, ukuran = ? WHERE id_minuman = ?";
            Connection conn = Koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);

            // Ambil dari textfield & combo
            pst.setString(1, tnama1.getText());
            pst.setString(2, cbka1.getSelectedItem().toString());
            pst.setInt(3, Integer.parseInt(tha1.getText()));
            pst.setString(4, cbu1.getSelectedItem().toString());
            pst.setInt(5, Integer.parseInt(tid1.getText())); // pakai String kalau ID di DB bertipe varchar

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");
            
            tampilData();
            clear();
            UpdateDialog.setVisible(false);

            // refresh tabel lewat parent
            

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_dupdateActionPerformed

    private void tha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tha2ActionPerformed

    private void byaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byaActionPerformed
        // TODO add your handling code here:
            try (Connection conn = Koneksi.getConnection()) {
                String id = tid.getText();
                String sql = "DELETE FROM dataminuman WHERE id_minuman = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, Integer.parseInt(id));
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                
                // refresh tabel di JFrame utama
                tampilData();
                clear();
                DeleteDialog.setVisible(false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
    }//GEN-LAST:event_byaActionPerformed

    private void bxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bxActionPerformed

    private void btidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btidakActionPerformed
        // TODO add your handling code here:
        DeleteDialog.setVisible(false);
    }//GEN-LAST:event_btidakActionPerformed

    private void bcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetakActionPerformed
        // TODO add your handling code here:                                      
    try {
        // Lokasi file laporan .jasper (hasil compile dari .jrxml)
        String reportPath = "src/Report/DataMinuman.jasper";
        
        // Ambil koneksi dari class Koneksi
        Connection conn = Koneksi.getConnection();

        // Isi laporan dengan data dari database PostgreSQL
        net.sf.jasperreports.engine.JasperPrint jp = 
            net.sf.jasperreports.engine.JasperFillManager.fillReport(reportPath, null, conn);

        // Tampilkan laporan di JasperViewer
        net.sf.jasperreports.view.JasperViewer.viewReport(jp, false);
        
    } catch (JRException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Gagal mencetak laporan: " + e.getMessage());
}
    }//GEN-LAST:event_bcetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dataminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dataminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dataminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dataminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dataminuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DeleteDialog;
    private javax.swing.JDialog InsertDialog;
    private javax.swing.JDialog UpdateDialog;
    private javax.swing.JButton bcetak;
    private javax.swing.JButton bd;
    private javax.swing.JButton bi;
    private javax.swing.JButton bsub;
    private javax.swing.JButton btidak;
    private javax.swing.JButton bu;
    private javax.swing.JButton bx;
    private javax.swing.JButton bya;
    private javax.swing.JComboBox<String> cbka;
    private javax.swing.JComboBox<String> cbka1;
    private javax.swing.JComboBox<String> cbka2;
    private javax.swing.JComboBox<String> cbu;
    private javax.swing.JComboBox<String> cbu1;
    private javax.swing.JComboBox<String> cbu2;
    private javax.swing.JButton dupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtab;
    private javax.swing.JTextField tha;
    private javax.swing.JTextField tha1;
    private javax.swing.JTextField tha2;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tid1;
    private javax.swing.JTextField tid2;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnama1;
    private javax.swing.JTextField tnama2;
    // End of variables declaration//GEN-END:variables
}
